files = """
	base64.c
	gw-browse.c
	gw-core.c
	gw-handlers.c
	gw-http.c
	gw-image.c
	gw-playlist.c
	gw-search.c
	gw-stream.c
	""".split()

def set_options(opt):
	pass

def configure(conf):
	import Options

	if Options.options.debug:
		conf.env['DEFINES_gateway'] = ['DEBUG']


	return True

def build(bld):
	obj = bld.new_task_gen('cc', 'program')
	obj.target = 'despotify-gateway'
	obj.includes = '. ../../lib'
	obj.source = files
	obj.defines = bld.env['DEFINES_gateway']
	obj.uselib_local = 'despotify'
	obj.install_path = '${PREFIX}/bin'
