#!/usr/bin/env python
import os
os.environ['WAFDIR'] = "."
os.environ['WAF_HOME'] = "_build_"

import sys
if sys.version_info < (2,4):
    raise "Waf requires Python >= 2.4"

import imp
imp.load_source("waf","waf-light")

