# vim: set fileencoding=utf-8 filetype=python :
from logging import fatal, info

srcdir = '.'
blddir = '_build_'

subdirs = ['lib', 'clients/despotify', 'clients/gateway', 'clients/simple']


def set_options(opt):
	opt.add_option('--debug', action = 'store_true', default = False,
	               help = 'Enable debug')

	for dir in subdirs:
		opt.sub_options(dir)


def configure(conf):
	conf.check_tool('gcc')

	for dir in subdirs:
		info('Configure %s:' % dir)
		success = conf.sub_config(dir)

		if not success:
			fatal('Configure %s failed' % dir)
			raise SystemExit(1)


def build(bld):
	bld.add_subdirs(subdirs)
